version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform...
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform --version
  pre_build:
    commands:
      - echo Initializing Terraform...
      - cd infrastructure/terraform
      - terraform init
  build:
    commands:
      - echo Running Terraform Apply for environment $TF_VAR_environment...
      - terraform apply -auto-approve
